### ISSUE TITLE
405: HTTP method POST is not supported by this URL

### ISSUE THREAD

**Issue by th3o6a1d** [kiegroup/optashift-employee-rostering#11]
Hi there,

Excited about this project. When I run locally using `gwt` `devmode` I get `405: HTTP method POST is not supported by this URL` whenever I try to add an employee, a skill, or shift. Have you encountered this? I'll bet it's a simple change to configuration of the dev server.

Jason

**Comment by ge0ffrey** [comment]
Did you fill in a name and a skill for that employee? I can reproduce an error if I forget to fill in an skill for a new employee.

We need to disable the "add" button if no skill or no name is filled in yet and give a clear message above the form.

**Comment by ge0ffrey** [comment]
This is fixed now.
