### ISSUE TITLE
External route show apache default page instead of apps page

### ISSUE THREAD

**Issue by vazh** [kiegroup/optashift-employee-rostering#32]
hello guys, im trying running this application in elementaryOS 0.4
previously i tried running this in W7, and it runs okay. it shows the apps.
but when i try running this in elementaryOS, its instead show apache2 ubuntu default page.
anybody know why this is happening?, what configuration do i miss?

**Comment by ge0ffrey** [comment]
This creates a war file that needs to be deployed on an app server such as WildFly or EAP.
Apache HTTP server isn't a java app server.
