### ISSUE TITLE
Repeatable shift rotation

### ISSUE THREAD

**Issue by oppsig** [kiegroup/optashift-employee-rostering#36]
Can optaplanner be used to find a optimal repeatable pattern for a 7 shift work schedule that spans over 7 weeks. Then it repeats itself. 
Want to make a work rotation were every shift work same shifts and hours during a 7 week schedule, were each shift is delayed by one week to another shift. It will also have to cover 24/7. Is this possible with optaplanner?

**Comment by ge0ffrey** [comment]
We're working on implementing it here in optashift-employee-rostering, here's the general idea:
https://raw.githubusercontent.com/kiegroup/optaplanner/master/optaplanner-docs/src/main/asciidoc/RepeatedPlanning/continuousPublishingWithRotation.png

**Comment by ge0ffrey** [comment]
This is implemented now.
