### ISSUE TITLE
Build fails on openshift (both local and online)

### ISSUE THREAD

**Issue by artemious7** [kiegroup/optashift-employee-rostering#62]
I followed the instructions in the readme file to build the app from this repo, but it fails every time. When I try it locally on my Windows 10 with Docker and the "oc.exe" tool, it simply hangs and the oc fails to open even the openshift local console (the one on localhost).

I've created an account on openshift (Starter: US East (Virginia) For individual learning and experimenting.)
When I do it in openshift online, it fails the build but doesn't tell me the reason.
Here are the logs:
http://pasted.co/47eed571

How can I deploy this app to openshift or to some other cloud (Google Cloud/Microsoft Azure etc.)

**Comment by artemious7** [comment]
Can anyone point me to the right direction?

**Comment by lacroixca** [comment]
It worked for me when increasing the VM memory limit to 4GB.

**Comment by ge0ffrey** [comment]
We've improved the README to help make it easier to run on OpenShift:
  https://github.com/kiegroup/optashift-employee-rostering/blob/master/README.adoc
Specifically OpenShift Online doesn't have enough resources to do the maven build there (GWT compilation fails with error code 137), but the ".provision.sh ... --binary" is a good workaround
